### ISSUE TITLE
['C:\\Users\\jatin\\Downloads\\Human-detection-and-Tracking-master\\Human-detection-and-Tracking-master\\video\\1.mp4'] (720, 1280, 3) (450, 800, 3) Traceback (most recent call last):   File "main.py", line 160, in <module>     temp = background_subtraction(previous_frame, frame_resized_grayscale, min_area)   File "main.py", line 118, in background_subtraction     im2, cnts, hierarchy = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by jatinbhoirjb** [ITCoders/Human-detection-and-Tracking#48]
# Issues should contain the following details which increases the probability of it get resolved quickly

* **Exact error or Issue details**
* **OpenCV Version**
* **Python Version**
* **Operating System**
* **Changes done, if any in the original code**

**Comment by jatinbhoirjb** [comment]
its problem is with opencv version
